# Generated by Django 4.0.6 on 2022-07-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('cat_image', models.ImageField(upload_to='categoryimage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('ram', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('laptop_image', models.ImageField(upload_to='adminmobile')),
                ('specifications', models.TextField()),
                ('description', models.TextField()),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_adminside.category')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('ram', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('laptop_image', models.ImageField(upload_to='adminlaptop')),
                ('specifications', models.TextField()),
                ('description', models.TextField()),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_adminside.category')),
            ],
        ),
    ]
