# Generated by Django 4.0.6 on 2022-07-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_adminside', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_mobile',
            old_name='laptop_image',
            new_name='mobile_image',
        ),
    ]
