# Generated by Django 4.0.6 on 2022-07-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_adminside', '0002_rename_laptop_image_category_mobile_mobile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('ram', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('laptop_image', models.ImageField(upload_to='adminlaptop')),
                ('specifications', models.TextField()),
                ('description', models.TextField()),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_adminside.category')),
            ],
        ),
    ]
