# Generated by Django 4.0.6 on 2022-07-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_adminside', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='laptop_image',
            field=models.ImageField(upload_to='product'),
        ),
    ]
