# Generated by Django 4.0.6 on 2022-07-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_adminside', '0004_alter_product_laptop_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='laptop_image',
            new_name='productimage',
        ),
    ]
