# Generated by Django 4.0.6 on 2022-07-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_adminside', '0005_rename_laptop_image_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_mobile',
            name='category_name',
        ),
        migrations.DeleteModel(
            name='Category_Laptop',
        ),
        migrations.DeleteModel(
            name='Category_Mobile',
        ),
    ]
