# Generated by Django 4.0.6 on 2022-07-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_adminside', '0006_remove_category_mobile_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(default=20, max_length=100),
        ),
    ]
