# Generated by Django 4.0.6 on 2022-08-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0020_remove_cartitem_variations'),
        ('category_adminside', '0009_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerimage', models.ImageField(upload_to='banner')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
