# Generated by Django 4.0.6 on 2022-08-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_adminside', '0011_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diccount_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
