# Generated by Django 3.2.15 on 2022-08-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_adminside', '0015_categoryoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='status',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Available', 'Available')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='status',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Available', 'Available')], max_length=120, null=True),
        ),
    ]
