# Generated by Django 3.2.15 on 2022-08-21 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_adminside', '0016_auto_20220821_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='status',
        ),
    ]
