# Generated by Django 3.2.15 on 2022-08-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_adminside', '0017_auto_20220821_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(null=True, upload_to='sideimage1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(null=True, upload_to='sideimage2'),
        ),
    ]
