# Generated by Django 4.0.6 on 2022-07-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_adminside', '0009_variation'),
        ('newcart', '0006_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='category_adminside.variation'),
        ),
    ]
