# Generated by Django 4.0.6 on 2022-07-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Out for shipping', 'Out for shipping'), ('cancelled', 'cancelled'), ('Completed', 'Completed')], default='pending', max_length=120),
        ),
    ]
