# Generated by Django 4.0.6 on 2022-07-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0010_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='subtotal',
            field=models.CharField(default=2000, max_length=200),
        ),
    ]
