# Generated by Django 4.0.6 on 2022-07-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0012_remove_orderproduct_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='Male', max_length=120),
        ),
    ]
