# Generated by Django 4.0.6 on 2022-07-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0014_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Out for shipping', 'Out for shipping'), ('Returned', 'Returned'), ('cancelled', 'cancelled'), ('Delivered', 'Delivered')], default='pending', max_length=120),
        ),
    ]
