# Generated by Django 4.0.6 on 2022-07-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='useremail',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
