# Generated by Django 4.0.6 on 2022-07-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0016_userprofile_useremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phonenumber', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('newaddress', models.TextField()),
                ('city', models.CharField(max_length=120)),
                ('pincode', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
