# Generated by Django 4.0.6 on 2022-08-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0020_remove_cartitem_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='useremail',
        ),
    ]
