# Generated by Django 4.0.6 on 2022-07-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0007_alter_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product_lap',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
