# Generated by Django 4.0.6 on 2022-07-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0009_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='product_lap',
            new_name='product',
        ),
    ]
