# Generated by Django 4.0.6 on 2022-07-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0012_remove_cartproduct_subtotal_alter_cartproduct_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='totalrate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
    ]
