# Generated by Django 4.0.6 on 2022-07-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0014_cartitem_delete_cartproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
