# Generated by Django 3.2.15 on 2022-08-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0016_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='carT',
        ),
        migrations.DeleteModel(
            name='CartPRODUCT',
        ),
    ]
